# Generated by Django 3.2.12 on 2022-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0005_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'Стажер'), ('2', 'Джуниор'), ('3', 'Миддл'), ('4', 'Синьор'), ('5', 'Лид')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Не ищу работу'), ('2', 'Рассматриваю предложения'), ('3', 'Ищу работу')], max_length=64, null=True),
        ),
    ]
