# Generated by Django 3.2.12 on 2022-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0007_alter_resume_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.CharField(max_length=64),
        ),
    ]
