# Generated by Django 3.2.12 on 2022-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0008_alter_resume_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(blank=True, choices=[('beg', 'Стажер'), ('jun', 'Джуниор'), ('mid', 'Миддл'), ('sin', 'Синьор'), ('lead', 'Лид')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(blank=True, choices=[('no', 'Не ищу работу'), ('look', 'Рассматриваю предложения'), ('search', 'Ищу работу')], max_length=64, null=True),
        ),
    ]
