# Generated by Django 3.2.12 on 2022-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0009_auto_20220324_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
