# Generated by Django 3.2.12 on 2022-03-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_service', '0010_alter_resume_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(max_length=64),
        ),
    ]
